# Generated by Django 2.2.3 on 2020-05-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200530_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='short_urls',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
