# Generated by Django 2.2.3 on 2020-05-30 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_short_urls_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='short_urls',
            name='clickedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
