# Generated by Django 3.0.6 on 2020-05-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_short_urls_clickeddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='short_urls',
            name='count',
        ),
    ]
