# Generated by Django 3.0.6 on 2020-05-31 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200531_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='short_urls',
            old_name='createdDate',
            new_name='clickedDate',
        ),
    ]
