# Generated by Django 3.0.6 on 2020-05-31 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_short_urls_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_urls',
            name='clickedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
